name: test

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jcheungshred/install-bazelisk@v1.0.1
      - name: check bazelisk
        run: bazelisk --version



